Type hints
threema-ch/threema-msgapi-sdk-python pull request #24
Opened 2016-11-25 13:40 UTC by dbrgn

What do you think about those? I think it improves legibility and tooling a lot, I had to guess the type of the arguments because there was no documentation (I first assumed hex string, then bytes, both of which were wrong).

2016-11-25 17:48 UTC, lgrahl commented
Sure, they'll be a great addition. You should rebase them onto the `develop` branch or wait until #21 has been merged. (Btw., although documentation isn't bad in general it's mostly missing for the callback server API.)

2017-04-22 11:34 UTC, dbrgn commented
- Rebased against develop
- Set up conditional `typing` dependency
- Set up type checking with mypy

2017-04-22 19:38 UTC, lgrahl commented
@dbrgn Can you rebase again? `requirements-dev.txt` shouldn't be necessary anymore (see new `setup.py`)

2017-04-22 22:33 UTC, dbrgn commented
@lgrahl done

2017-04-23 14:09 UTC, lgrahl requested changes
Looks good so far. Can you add usage of mypy to the readme?

2017-04-23 14:09 UTC, lgrahl commented on setup.py
> +    'mypy==0.501',
Any reason why this exact version? :)

2017-04-23 14:51 UTC, dbrgn commented on setup.py
> +    'mypy==0.501',
It's just the current version. But pinning it avoids breaking of the testsuite if mypy pushes a new release with additional checks. It's probably better to simply bump the version from time to time.

2017-04-23 15:05 UTC, lgrahl commented on setup.py
> +    'mypy==0.501',
It's a bit weird that we use non-pinned dependencies for all the other tools but fair enough, I get your point. :)

2017-04-23 15:06 UTC, lgrahl approved these changes

2017-04-23 15:57 UTC, merged