Maintenance update of dependencies
threema-ch/threema-msgapi-sdk-python pull request #69
Opened 2024-08-20 22:09 UTC by threema-lenny

2024-08-20 23:28 UTC, threema-lenny commented
Once merged, I'll follow up with a release. :slightly_smiling_face:

2024-08-20 23:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/threema-ch/threema-msgapi-sdk-python?pullRequest=69) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/threema-ch/threema-msgapi-sdk-python?pullRequest=69) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: threema-lenny<br/>:white_check_mark: bbolli<br/>:x: threema-eduard<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/threema-ch/threema-msgapi-sdk-python?pullRequest=69) it.</sub>

2024-08-21 15:45 UTC, threema-eduard requested changes

2024-08-21 15:45 UTC, threema-eduard commented on CHANGELOG.rst
> +- Add support for Python 3.10 and Python 3.11
what about Python 3.12? 3.10 was already supported AFAIK.

2024-08-21 15:45 UTC, threema-eduard commented on CHANGELOG.rst
> +- Add support for Python 3.10 and Python 3.11
And shouldn't the new "GATEWAY_API_URL" env option be mentioned?

2024-08-21 15:46 UTC, threema-eduard commented
LGTM apart from the little comments above!

2024-08-21 15:46 UTC, threema-lenny commented on threema/gateway/bin/gateway_client.py
> +@click.argument('caption', required=False)
Good addition. But I think I'd prefer a `@click.option` here. :slightly_smiling_face:

2024-08-21 15:47 UTC, threema-eduard commented on threema/gateway/bin/gateway_client.py
> +@click.argument('caption', required=False)
1 sec

2024-08-21 16:16 UTC, threema-lenny commented on CHANGELOG.rst
> +- Add support for Python 3.10 and Python 3.11
Fixed!

2024-08-21 17:12 UTC, threema-eduard approved these changes

2024-08-21 18:00 UTC, merged